//go:build !ignore_autogenerated

/*
Copyright 2026.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuildCloudInit) DeepCopyInto(out *BuildCloudInit) {
	*out = *in
	if in.UserDataFrom != nil {
		in, out := &in.UserDataFrom, &out.UserDataFrom
		*out = new(ConfigMapOrSecretReference)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuildCloudInit.
func (in *BuildCloudInit) DeepCopy() *BuildCloudInit {
	if in == nil {
		return nil
	}
	out := new(BuildCloudInit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuildCommunicator) DeepCopyInto(out *BuildCommunicator) {
	*out = *in
	if in.SSHPrivateKeySecret != nil {
		in, out := &in.SSHPrivateKeySecret, &out.SSHPrivateKeySecret
		*out = new(SecretKeyReference)
		**out = **in
	}
	if in.SSHTimeout != nil {
		in, out := &in.SSHTimeout, &out.SSHTimeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuildCommunicator.
func (in *BuildCommunicator) DeepCopy() *BuildCommunicator {
	if in == nil {
		return nil
	}
	out := new(BuildCommunicator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuildDisk) DeepCopyInto(out *BuildDisk) {
	*out = *in
	out.Size = in.Size.DeepCopy()
	if in.StorageClass != nil {
		in, out := &in.StorageClass, &out.StorageClass
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuildDisk.
func (in *BuildDisk) DeepCopy() *BuildDisk {
	if in == nil {
		return nil
	}
	out := new(BuildDisk)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuildFile) DeepCopyInto(out *BuildFile) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuildFile.
func (in *BuildFile) DeepCopy() *BuildFile {
	if in == nil {
		return nil
	}
	out := new(BuildFile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuildOutput) DeepCopyInto(out *BuildOutput) {
	*out = *in
	if in.VMs != nil {
		in, out := &in.VMs, &out.VMs
		*out = make([]VMOutput, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuildOutput.
func (in *BuildOutput) DeepCopy() *BuildOutput {
	if in == nil {
		return nil
	}
	out := new(BuildOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuildOverrides) DeepCopyInto(out *BuildOverrides) {
	*out = *in
	if in.VPCs != nil {
		in, out := &in.VPCs, &out.VPCs
		*out = make([]VPCOverride, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Subnets != nil {
		in, out := &in.Subnets, &out.Subnets
		*out = make([]SubnetOverride, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VMs != nil {
		in, out := &in.VMs, &out.VMs
		*out = make([]BuildVMOverride, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuildOverrides.
func (in *BuildOverrides) DeepCopy() *BuildOverrides {
	if in == nil {
		return nil
	}
	out := new(BuildOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuildProvisioner) DeepCopyInto(out *BuildProvisioner) {
	*out = *in
	if in.Shell != nil {
		in, out := &in.Shell, &out.Shell
		*out = new(ShellProvisioner)
		(*in).DeepCopyInto(*out)
	}
	if in.File != nil {
		in, out := &in.File, &out.File
		*out = new(FileProvisioner)
		(*in).DeepCopyInto(*out)
	}
	if in.Reboot != nil {
		in, out := &in.Reboot, &out.Reboot
		*out = new(RebootProvisioner)
		**out = **in
	}
	if in.WindowsUpdate != nil {
		in, out := &in.WindowsUpdate, &out.WindowsUpdate
		*out = new(WindowsUpdateProvisioner)
		(*in).DeepCopyInto(*out)
	}
	if in.Handbuild != nil {
		in, out := &in.Handbuild, &out.Handbuild
		*out = new(HandbuildProvisioner)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuildProvisioner.
func (in *BuildProvisioner) DeepCopy() *BuildProvisioner {
	if in == nil {
		return nil
	}
	out := new(BuildProvisioner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuildReference) DeepCopyInto(out *BuildReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuildReference.
func (in *BuildReference) DeepCopy() *BuildReference {
	if in == nil {
		return nil
	}
	out := new(BuildReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuildResources) DeepCopyInto(out *BuildResources) {
	*out = *in
	out.Memory = in.Memory.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuildResources.
func (in *BuildResources) DeepCopy() *BuildResources {
	if in == nil {
		return nil
	}
	out := new(BuildResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuildSource) DeepCopyInto(out *BuildSource) {
	*out = *in
	if in.SourcePVC != nil {
		in, out := &in.SourcePVC, &out.SourcePVC
		*out = new(PVCReference)
		**out = **in
	}
	if in.BuildRef != nil {
		in, out := &in.BuildRef, &out.BuildRef
		*out = new(BuildReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuildSource.
func (in *BuildSource) DeepCopy() *BuildSource {
	if in == nil {
		return nil
	}
	out := new(BuildSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuildVM) DeepCopyInto(out *BuildVM) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Disks != nil {
		in, out := &in.Disks, &out.Disks
		*out = make([]BuildDisk, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Communicator.DeepCopyInto(&out.Communicator)
	if in.CloudInit != nil {
		in, out := &in.CloudInit, &out.CloudInit
		*out = new(BuildCloudInit)
		(*in).DeepCopyInto(*out)
	}
	if in.NICs != nil {
		in, out := &in.NICs, &out.NICs
		*out = make([]VMNIC, len(*in))
		copy(*out, *in)
	}
	if in.BootCommand != nil {
		in, out := &in.BootCommand, &out.BootCommand
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EFIFirmware != nil {
		in, out := &in.EFIFirmware, &out.EFIFirmware
		*out = new(EFIFirmware)
		**out = **in
	}
	if in.Provisioners != nil {
		in, out := &in.Provisioners, &out.Provisioners
		*out = make([]BuildProvisioner, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ISOs != nil {
		in, out := &in.ISOs, &out.ISOs
		*out = make([]ISOSource, len(*in))
		copy(*out, *in)
	}
	if in.Floppy != nil {
		in, out := &in.Floppy, &out.Floppy
		*out = new(Floppy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuildVM.
func (in *BuildVM) DeepCopy() *BuildVM {
	if in == nil {
		return nil
	}
	out := new(BuildVM)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuildVMOverride) DeepCopyInto(out *BuildVMOverride) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(BuildResources)
		(*in).DeepCopyInto(*out)
	}
	if in.NICs != nil {
		in, out := &in.NICs, &out.NICs
		*out = make([]VMNIC, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuildVMOverride.
func (in *BuildVMOverride) DeepCopy() *BuildVMOverride {
	if in == nil {
		return nil
	}
	out := new(BuildVMOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloneNetworkStatus) DeepCopyInto(out *CloneNetworkStatus) {
	*out = *in
	if in.VPCsCreated != nil {
		in, out := &in.VPCsCreated, &out.VPCsCreated
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SubnetsCreated != nil {
		in, out := &in.SubnetsCreated, &out.SubnetsCreated
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EgressGatewaysCreated != nil {
		in, out := &in.EgressGatewaysCreated, &out.EgressGatewaysCreated
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloneNetworkStatus.
func (in *CloneNetworkStatus) DeepCopy() *CloneNetworkStatus {
	if in == nil {
		return nil
	}
	out := new(CloneNetworkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloneVolumeStatus) DeepCopyInto(out *CloneVolumeStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloneVolumeStatus.
func (in *CloneVolumeStatus) DeepCopy() *CloneVolumeStatus {
	if in == nil {
		return nil
	}
	out := new(CloneVolumeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClonedVMStatus) DeepCopyInto(out *ClonedVMStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClonedVMStatus.
func (in *ClonedVMStatus) DeepCopy() *ClonedVMStatus {
	if in == nil {
		return nil
	}
	out := new(ClonedVMStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapOrSecretReference) DeepCopyInto(out *ConfigMapOrSecretReference) {
	*out = *in
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(corev1.ConfigMapKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapOrSecretReference.
func (in *ConfigMapOrSecretReference) DeepCopy() *ConfigMapOrSecretReference {
	if in == nil {
		return nil
	}
	out := new(ConfigMapOrSecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataVolumeOutput) DeepCopyInto(out *DataVolumeOutput) {
	*out = *in
	if in.StorageClass != nil {
		in, out := &in.StorageClass, &out.StorageClass
		*out = new(string)
		**out = **in
	}
	if in.AccessModes != nil {
		in, out := &in.AccessModes, &out.AccessModes
		*out = make([]corev1.PersistentVolumeAccessMode, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataVolumeOutput.
func (in *DataVolumeOutput) DeepCopy() *DataVolumeOutput {
	if in == nil {
		return nil
	}
	out := new(DataVolumeOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EFIFirmware) DeepCopyInto(out *EFIFirmware) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EFIFirmware.
func (in *EFIFirmware) DeepCopy() *EFIFirmware {
	if in == nil {
		return nil
	}
	out := new(EFIFirmware)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EgressGatewaySpec) DeepCopyInto(out *EgressGatewaySpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EgressGatewaySpec.
func (in *EgressGatewaySpec) DeepCopy() *EgressGatewaySpec {
	if in == nil {
		return nil
	}
	out := new(EgressGatewaySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileProvisioner) DeepCopyInto(out *FileProvisioner) {
	*out = *in
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(ConfigMapOrSecretReference)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileProvisioner.
func (in *FileProvisioner) DeepCopy() *FileProvisioner {
	if in == nil {
		return nil
	}
	out := new(FileProvisioner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Floppy) DeepCopyInto(out *Floppy) {
	*out = *in
	if in.Files != nil {
		in, out := &in.Files, &out.Files
		*out = make([]FloppyFileRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Floppy.
func (in *Floppy) DeepCopy() *Floppy {
	if in == nil {
		return nil
	}
	out := new(Floppy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FloppyFileRef) DeepCopyInto(out *FloppyFileRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FloppyFileRef.
func (in *FloppyFileRef) DeepCopy() *FloppyFileRef {
	if in == nil {
		return nil
	}
	out := new(FloppyFileRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GradeCommandResult) DeepCopyInto(out *GradeCommandResult) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GradeCommandResult.
func (in *GradeCommandResult) DeepCopy() *GradeCommandResult {
	if in == nil {
		return nil
	}
	out := new(GradeCommandResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GradeRequest) DeepCopyInto(out *GradeRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GradeRequest.
func (in *GradeRequest) DeepCopy() *GradeRequest {
	if in == nil {
		return nil
	}
	out := new(GradeRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GradeRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GradeRequestList) DeepCopyInto(out *GradeRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GradeRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GradeRequestList.
func (in *GradeRequestList) DeepCopy() *GradeRequestList {
	if in == nil {
		return nil
	}
	out := new(GradeRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GradeRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GradeRequestSpec) DeepCopyInto(out *GradeRequestSpec) {
	*out = *in
	if in.VMs != nil {
		in, out := &in.VMs, &out.VMs
		*out = make([]GradeVM, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Commands != nil {
		in, out := &in.Commands, &out.Commands
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GradeRequestSpec.
func (in *GradeRequestSpec) DeepCopy() *GradeRequestSpec {
	if in == nil {
		return nil
	}
	out := new(GradeRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GradeRequestStatus) DeepCopyInto(out *GradeRequestStatus) {
	*out = *in
	if in.VMStatuses != nil {
		in, out := &in.VMStatuses, &out.VMStatuses
		*out = make([]GradeVMStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GradeRequestStatus.
func (in *GradeRequestStatus) DeepCopy() *GradeRequestStatus {
	if in == nil {
		return nil
	}
	out := new(GradeRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GradeVM) DeepCopyInto(out *GradeVM) {
	*out = *in
	if in.Commands != nil {
		in, out := &in.Commands, &out.Commands
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GradeVM.
func (in *GradeVM) DeepCopy() *GradeVM {
	if in == nil {
		return nil
	}
	out := new(GradeVM)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GradeVMStatus) DeepCopyInto(out *GradeVMStatus) {
	*out = *in
	if in.Results != nil {
		in, out := &in.Results, &out.Results
		*out = make([]GradeCommandResult, len(*in))
		copy(*out, *in)
	}
	if in.BootStartedAt != nil {
		in, out := &in.BootStartedAt, &out.BootStartedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GradeVMStatus.
func (in *GradeVMStatus) DeepCopy() *GradeVMStatus {
	if in == nil {
		return nil
	}
	out := new(GradeVMStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HandbuildProvisioner) DeepCopyInto(out *HandbuildProvisioner) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HandbuildProvisioner.
func (in *HandbuildProvisioner) DeepCopy() *HandbuildProvisioner {
	if in == nil {
		return nil
	}
	out := new(HandbuildProvisioner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpDirectory) DeepCopyInto(out *HttpDirectory) {
	*out = *in
	if in.Files != nil {
		in, out := &in.Files, &out.Files
		*out = make([]HttpDirectoryFileRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpDirectory.
func (in *HttpDirectory) DeepCopy() *HttpDirectory {
	if in == nil {
		return nil
	}
	out := new(HttpDirectory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HttpDirectoryFileRef) DeepCopyInto(out *HttpDirectoryFileRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HttpDirectoryFileRef.
func (in *HttpDirectoryFileRef) DeepCopy() *HttpDirectoryFileRef {
	if in == nil {
		return nil
	}
	out := new(HttpDirectoryFileRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ISOSource) DeepCopyInto(out *ISOSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ISOSource.
func (in *ISOSource) DeepCopy() *ISOSource {
	if in == nil {
		return nil
	}
	out := new(ISOSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Network) DeepCopyInto(out *Network) {
	*out = *in
	if in.VPCs != nil {
		in, out := &in.VPCs, &out.VPCs
		*out = make([]VPC, len(*in))
		copy(*out, *in)
	}
	if in.Subnets != nil {
		in, out := &in.Subnets, &out.Subnets
		*out = make([]Subnet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Network.
func (in *Network) DeepCopy() *Network {
	if in == nil {
		return nil
	}
	out := new(Network)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkStatus) DeepCopyInto(out *NetworkStatus) {
	*out = *in
	if in.VPCsCreated != nil {
		in, out := &in.VPCsCreated, &out.VPCsCreated
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SubnetsCreated != nil {
		in, out := &in.SubnetsCreated, &out.SubnetsCreated
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkStatus.
func (in *NetworkStatus) DeepCopy() *NetworkStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PVCReference) DeepCopyInto(out *PVCReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PVCReference.
func (in *PVCReference) DeepCopy() *PVCReference {
	if in == nil {
		return nil
	}
	out := new(PVCReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProvisionerResult) DeepCopyInto(out *ProvisionerResult) {
	*out = *in
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProvisionerResult.
func (in *ProvisionerResult) DeepCopy() *ProvisionerResult {
	if in == nil {
		return nil
	}
	out := new(ProvisionerResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RebootProvisioner) DeepCopyInto(out *RebootProvisioner) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RebootProvisioner.
func (in *RebootProvisioner) DeepCopy() *RebootProvisioner {
	if in == nil {
		return nil
	}
	out := new(RebootProvisioner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3ExportOutput) DeepCopyInto(out *S3ExportOutput) {
	*out = *in
	out.CredentialsSecret = in.CredentialsSecret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3ExportOutput.
func (in *S3ExportOutput) DeepCopy() *S3ExportOutput {
	if in == nil {
		return nil
	}
	out := new(S3ExportOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3ExportStatus) DeepCopyInto(out *S3ExportStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3ExportStatus.
func (in *S3ExportStatus) DeepCopy() *S3ExportStatus {
	if in == nil {
		return nil
	}
	out := new(S3ExportStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyReference) DeepCopyInto(out *SecretKeyReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyReference.
func (in *SecretKeyReference) DeepCopy() *SecretKeyReference {
	if in == nil {
		return nil
	}
	out := new(SecretKeyReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShellProvisioner) DeepCopyInto(out *ShellProvisioner) {
	*out = *in
	if in.ScriptFrom != nil {
		in, out := &in.ScriptFrom, &out.ScriptFrom
		*out = new(ConfigMapOrSecretReference)
		(*in).DeepCopyInto(*out)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShellProvisioner.
func (in *ShellProvisioner) DeepCopy() *ShellProvisioner {
	if in == nil {
		return nil
	}
	out := new(ShellProvisioner)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Subnet) DeepCopyInto(out *Subnet) {
	*out = *in
	if in.DHCP != nil {
		in, out := &in.DHCP, &out.DHCP
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Subnet.
func (in *Subnet) DeepCopy() *Subnet {
	if in == nil {
		return nil
	}
	out := new(Subnet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubnetOverride) DeepCopyInto(out *SubnetOverride) {
	*out = *in
	if in.Unmanaged != nil {
		in, out := &in.Unmanaged, &out.Unmanaged
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubnetOverride.
func (in *SubnetOverride) DeepCopy() *SubnetOverride {
	if in == nil {
		return nil
	}
	out := new(SubnetOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMBuildStatus) DeepCopyInto(out *VMBuildStatus) {
	*out = *in
	if in.ProvisionerResults != nil {
		in, out := &in.ProvisionerResults, &out.ProvisionerResults
		*out = make([]ProvisionerResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMBuildStatus.
func (in *VMBuildStatus) DeepCopy() *VMBuildStatus {
	if in == nil {
		return nil
	}
	out := new(VMBuildStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMNIC) DeepCopyInto(out *VMNIC) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMNIC.
func (in *VMNIC) DeepCopy() *VMNIC {
	if in == nil {
		return nil
	}
	out := new(VMNIC)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMOutput) DeepCopyInto(out *VMOutput) {
	*out = *in
	in.DataVolume.DeepCopyInto(&out.DataVolume)
	if in.S3Export != nil {
		in, out := &in.S3Export, &out.S3Export
		*out = new(S3ExportOutput)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMOutput.
func (in *VMOutput) DeepCopy() *VMOutput {
	if in == nil {
		return nil
	}
	out := new(VMOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VMOverride) DeepCopyInto(out *VMOverride) {
	*out = *in
	if in.NICs != nil {
		in, out := &in.NICs, &out.NICs
		*out = make([]VMNIC, len(*in))
		copy(*out, *in)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(BuildResources)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VMOverride.
func (in *VMOverride) DeepCopy() *VMOverride {
	if in == nil {
		return nil
	}
	out := new(VMOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPC) DeepCopyInto(out *VPC) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPC.
func (in *VPC) DeepCopy() *VPC {
	if in == nil {
		return nil
	}
	out := new(VPC)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCOverride) DeepCopyInto(out *VPCOverride) {
	*out = *in
	if in.Internet != nil {
		in, out := &in.Internet, &out.Internet
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCOverride.
func (in *VPCOverride) DeepCopy() *VPCOverride {
	if in == nil {
		return nil
	}
	out := new(VPCOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineBuild) DeepCopyInto(out *VirtualMachineBuild) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineBuild.
func (in *VirtualMachineBuild) DeepCopy() *VirtualMachineBuild {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineBuild)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineBuild) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineBuildList) DeepCopyInto(out *VirtualMachineBuildList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirtualMachineBuild, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineBuildList.
func (in *VirtualMachineBuildList) DeepCopy() *VirtualMachineBuildList {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineBuildList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineBuildList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineBuildSpec) DeepCopyInto(out *VirtualMachineBuildSpec) {
	*out = *in
	if in.VMs != nil {
		in, out := &in.VMs, &out.VMs
		*out = make([]BuildVM, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Files != nil {
		in, out := &in.Files, &out.Files
		*out = make([]BuildFile, len(*in))
		copy(*out, *in)
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(Network)
		(*in).DeepCopyInto(*out)
	}
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(BuildOutput)
		(*in).DeepCopyInto(*out)
	}
	if in.S3Export != nil {
		in, out := &in.S3Export, &out.S3Export
		*out = new(S3ExportOutput)
		**out = **in
	}
	if in.HttpDirectory != nil {
		in, out := &in.HttpDirectory, &out.HttpDirectory
		*out = new(HttpDirectory)
		(*in).DeepCopyInto(*out)
	}
	if in.BuildOverrides != nil {
		in, out := &in.BuildOverrides, &out.BuildOverrides
		*out = new(BuildOverrides)
		(*in).DeepCopyInto(*out)
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.ISOCacheTTL != nil {
		in, out := &in.ISOCacheTTL, &out.ISOCacheTTL
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineBuildSpec.
func (in *VirtualMachineBuildSpec) DeepCopy() *VirtualMachineBuildSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineBuildSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineBuildStatus) DeepCopyInto(out *VirtualMachineBuildStatus) {
	*out = *in
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(NetworkStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.VMStatuses != nil {
		in, out := &in.VMStatuses, &out.VMStatuses
		*out = make([]VMBuildStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.S3Exports != nil {
		in, out := &in.S3Exports, &out.S3Exports
		*out = make([]S3ExportStatus, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineBuildStatus.
func (in *VirtualMachineBuildStatus) DeepCopy() *VirtualMachineBuildStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineBuildStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineClone) DeepCopyInto(out *VirtualMachineClone) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineClone.
func (in *VirtualMachineClone) DeepCopy() *VirtualMachineClone {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineClone)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineClone) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineCloneList) DeepCopyInto(out *VirtualMachineCloneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirtualMachineClone, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineCloneList.
func (in *VirtualMachineCloneList) DeepCopy() *VirtualMachineCloneList {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineCloneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineCloneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineCloneSpec) DeepCopyInto(out *VirtualMachineCloneSpec) {
	*out = *in
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(Network)
		(*in).DeepCopyInto(*out)
	}
	if in.VMOverrides != nil {
		in, out := &in.VMOverrides, &out.VMOverrides
		*out = make([]VMOverride, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.EgressGateway != nil {
		in, out := &in.EgressGateway, &out.EgressGateway
		*out = new(EgressGatewaySpec)
		(*in).DeepCopyInto(*out)
	}
	if in.AgeAnchor != nil {
		in, out := &in.AgeAnchor, &out.AgeAnchor
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineCloneSpec.
func (in *VirtualMachineCloneSpec) DeepCopy() *VirtualMachineCloneSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineCloneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineCloneStatus) DeepCopyInto(out *VirtualMachineCloneStatus) {
	*out = *in
	if in.VolumeStates != nil {
		in, out := &in.VolumeStates, &out.VolumeStates
		*out = make([]CloneVolumeStatus, len(*in))
		copy(*out, *in)
	}
	if in.VMStatuses != nil {
		in, out := &in.VMStatuses, &out.VMStatuses
		*out = make([]ClonedVMStatus, len(*in))
		copy(*out, *in)
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(CloneNetworkStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.AgeAnchor != nil {
		in, out := &in.AgeAnchor, &out.AgeAnchor
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineCloneStatus.
func (in *VirtualMachineCloneStatus) DeepCopy() *VirtualMachineCloneStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineCloneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineNamespace) DeepCopyInto(out *VirtualMachineNamespace) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineNamespace.
func (in *VirtualMachineNamespace) DeepCopy() *VirtualMachineNamespace {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineNamespace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineNamespace) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineNamespaceList) DeepCopyInto(out *VirtualMachineNamespaceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VirtualMachineNamespace, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineNamespaceList.
func (in *VirtualMachineNamespaceList) DeepCopy() *VirtualMachineNamespaceList {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineNamespaceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VirtualMachineNamespaceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineNamespaceNetwork) DeepCopyInto(out *VirtualMachineNamespaceNetwork) {
	*out = *in
	if in.VPCs != nil {
		in, out := &in.VPCs, &out.VPCs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Subnets != nil {
		in, out := &in.Subnets, &out.Subnets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineNamespaceNetwork.
func (in *VirtualMachineNamespaceNetwork) DeepCopy() *VirtualMachineNamespaceNetwork {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineNamespaceNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineNamespaceOwnerRef) DeepCopyInto(out *VirtualMachineNamespaceOwnerRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineNamespaceOwnerRef.
func (in *VirtualMachineNamespaceOwnerRef) DeepCopy() *VirtualMachineNamespaceOwnerRef {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineNamespaceOwnerRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineNamespaceSpec) DeepCopyInto(out *VirtualMachineNamespaceSpec) {
	*out = *in
	if in.OwnerRef != nil {
		in, out := &in.OwnerRef, &out.OwnerRef
		*out = new(VirtualMachineNamespaceOwnerRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineNamespaceSpec.
func (in *VirtualMachineNamespaceSpec) DeepCopy() *VirtualMachineNamespaceSpec {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineNamespaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineNamespaceStatus) DeepCopyInto(out *VirtualMachineNamespaceStatus) {
	*out = *in
	if in.VMs != nil {
		in, out := &in.VMs, &out.VMs
		*out = make([]VirtualMachineNamespaceVM, len(*in))
		copy(*out, *in)
	}
	if in.Network != nil {
		in, out := &in.Network, &out.Network
		*out = new(VirtualMachineNamespaceNetwork)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineNamespaceStatus.
func (in *VirtualMachineNamespaceStatus) DeepCopy() *VirtualMachineNamespaceStatus {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineNamespaceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VirtualMachineNamespaceVM) DeepCopyInto(out *VirtualMachineNamespaceVM) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VirtualMachineNamespaceVM.
func (in *VirtualMachineNamespaceVM) DeepCopy() *VirtualMachineNamespaceVM {
	if in == nil {
		return nil
	}
	out := new(VirtualMachineNamespaceVM)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WindowsUpdateProvisioner) DeepCopyInto(out *WindowsUpdateProvisioner) {
	*out = *in
	if in.Filters != nil {
		in, out := &in.Filters, &out.Filters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WindowsUpdateProvisioner.
func (in *WindowsUpdateProvisioner) DeepCopy() *WindowsUpdateProvisioner {
	if in == nil {
		return nil
	}
	out := new(WindowsUpdateProvisioner)
	in.DeepCopyInto(out)
	return out
}
