{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "aileron.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aileron.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "aileron.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: metrics
  endpoints:
    - port: metrics
      path: /metrics
      scheme: http
      interval: {{ .Values.metrics.serviceMonitor.interval }}
{{- end }}
